### PR TITLE
Updated Rework branch to 1.12.2

### PR DESCRIPTION
**Pull request by dmf444**
Updated TMechworks current state to 1.12.2, and fixed Extending drawbridge and normal one.

Implemented a json based blacklist, and made a quick TESR for the disguise mode.
Seems to work both SP and SMP, I've got it running on my dedicated server.

Note: Couldn't get HWAILA to load from gradle, so I'm building directly from the /libs folder.

### CODE REVIEW

**Comment by fuj1n** [comment]
Have only now seen this. I will look through your code and manually merge parts I haven't done yet, thank you.

**Comment by dmf444** [comment]
Alright cool. I have found one more issue, I’m trying to fix it in my fork.

**Comment by fuj1n** [comment]
What is the issue if you don't mind me asking?

**Comment by dmf444** [comment]
If a bridge is extending, but runs out of blocks, when it tries to retract the blocks are removed from the world but not put back into the inventory. If there is at least one block still in the inventory, everything works out fine

**Comment by Waterpicker** [comment]
Please tell me this legit. :D I like some of the stuff from this mod.

**Comment by dmf444** [comment]
@fuj1n pulled your latest code to into this push, not sure if you want to still use any of it.

**Comment by fuj1n** [comment]
1.14 update is an almost complete rewrite, so this no longer applies

**Pull request closed without merging**
